version: "3.9"

services:
  mysql:
    ports:
      - "3307:3306"  # Different port to avoid conflict with local MySQL

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./uploads:/app/uploads
      - ./node_modules:/app/node_modules
    command: npm run dev